Add the capability to analyze wave height and 10-m wind gust into HRRR-3DRTMA package. 1. GSI source code would be git-cloned from github repository; 2. Add steps in workflow (ex-scripts, j-job scripts, xml files; 3. some updated fix files (anavonfo,convinfo under fix/gsi) and parm file    (gsiparm.anl.sh under parm/gsi) are NOT included in this pacakge.

diff --git a/jobs/JRTMA3D_ANLDUMP b/jobs/JRTMA3D_ANLDUMP
--- a/jobs/JRTMA3D_ANLDUMP
+++ b/jobs/JRTMA3D_ANLDUMP
@@ -88,22 +88,16 @@ export FIXgsi=${FIXgsi:-"${FIXrtma3d}/gsi"}
 export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${NET}.${PDY}}
 export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${NET}.${PDY}}
 
-# Directory to store the firstguess as input for the RTMA3D (NETCDF?) 
+### 3DRTMA GSIANL Products (netcdf)
+export COMOUTgsi_rtma3d=${COMOUTgsi_rtma3d:-"${COMOUT}/gsiprd.${cycle}"}
 
-export COMINrap=${COMINRAP}/rap.${PDY}
-export COMINhrrr=${COMINHRRR}/hrrr.${PDY}/${NET}
-export GESINhrrr=${GESINHRRR}
-export GESINhrrrm1=${GESINHRRR}
+# Directory to store the firstguess as input for the RTMA3D (NETCDF?) 
 
 export GESINhrrr_rtma3d=${GESINhrrr_rtma3d:-"${COMIN}/fgsprd.${cycle}"}
 export PDYHH_cycm1=$($NDATE -01  "${PDYHH}")
 export PDYHH_cycp1=$($NDATE +01  "${PDYHH}")
 
 PDY_cycp1=`echo ${PDYHH_cycp1} | cut -c 1-8`
-
-export COMINhrrr_cycp1=${COMINHRRR}/hrrr.${PDY_cycp1}/${NET}
-
-export FGS_OPT=${FGS_OPT:-1}
 
 # set the file name of the firstguess for rtma3d
 if [ ! "${PROD_HEAD}" ] ; then
@@ -114,37 +108,20 @@ else
   export FGSrtma3d_FNAME="${PROD_HEAD}.firstguess.nc"
 fi
  
-# Define the path to WW3 firstguess for HOWV
-export COMINww3GL=${COMINww3GL:-/lfs/h1/ops/prod/com/glwu/v2.0}                                 # v1.1 is old
-export COMINww3=${COMINww3:-/lfs/h1/ops/prod/com/gfs/v16.3}                                  # v16.2 is old
-
 # path to the scripts
 export HOMEscript=${SCRIPT_DIR}
 
 if [ ! -d "${COMOUT}" ] ; then
-   mkdir -p $COMOUT
+   echo "ERROR: ${COMOUT} does not exist!"
+   exit 1
 fi
-
-if [ ! -d "${GESINhrrr_rtma3d}" ] ; then
-   mkdir -p $GESINhrrr_rtma3d
-fi
-
-# fgs data from HPSS
-#if [ ! -d "${COMINhrrr}" ] ; then
-#  ${ECHO} "ERROR: ${COMINhrrr} does not exist!"
-#  exit 1
-#fi
-#if [ ! -d "${COMINhrrr_cycp1}" ] ; then
-#  ${ECHO} "ERROR: ${COMINhrrr_cycp1} does not exist!"
-#  exit 1
-#fi
 
 ###########################################################
 
 ######################
 # Execute the script.
 ######################
-${exSCR_PREPFGS:-$HOMErtma3d/scripts/$RUN/ex${RUN}_prepfgs.ksh}
+${exSCR_ANLDUMP:-$HOMErtma3d/scripts/$RUN/ex${RUN}_anldump.ksh}
 export err=$?; err_chk
 
 msg="$0 of $job completed normally"
