Removing RAP_E from the list of paths used in processing. Also repairing the real-time, hourly workflow for WCOSS.

diff --git a/jobs/JRTMA3D_PREPFGS_RT b/jobs/JRTMA3D_PREPFGS_RT
--- a/jobs/JRTMA3D_PREPFGS_RT
+++ b/jobs/JRTMA3D_PREPFGS_RT
@@ -21,6 +21,7 @@ export NET=${NET:-rtma3d}
 export RUN=${RUN:-rtma3d}
 export model=${model:-rtma3d}
 
+export domain=${domain:-conus}
 ##########################################################
 # obtain unique process id (pid)
 ##########################################################
@@ -46,20 +47,21 @@ cd $DATA
 #    setpdy.sh needs the variables 
 #    $PDY and $cyc already defined in advance
 #####################################################
-export cycle=${cycle:-t${cyc}${subcyc}z}
+export cycle=${cycle:-t${cyc}z} 
 #setpdy.sh
 #. ${DATA}/PDY
 
 export subcyc=${subcyc} #Note: Must define subcyc in upper level script. Can be 00, 15, 30, or 45 /MPondeca, 30Jun2017
                          #only used for rurtma2p5
 export PDYHH="${PDY}${cyc}"
+
 ####################################
 # Determine Job Output Name on System
 ####################################
 export LOG_JJOB=${LOG_JJOB:-$COMROOT/logs/jlogfiles}
 export jlogfile=${jlogfile:-$LOG_JJOB/jlogfile.${jobid}}
 # export pgmout=${pgmout:-"OUTPUT.$$"}
-export pgmout=${pgmout:-"OUTPUT.${PDY}${cyc}${subcyc}.${jobid}"}
+export pgmout=${pgmout:-"OUTPUT.${PDY}${cyc}.${jobid}"}
 if [ ! -d ${LOG_JJOB} ] ; then
    mkdir -p ${LOG_JJOB}
 fi
@@ -78,71 +80,60 @@ export PARMrtma3d=${PARMrtma3d:-$HOMErtma3d/parm/${RUN}}
 export USHrtma3d=${USHrtma3d:-$HOMErtma3d/ush/${RUN}}
 export UTILrtma3d=${UTILrtma3d:-$HOMErtma3d/util/${RUN}}
 
-# date and time for previous and next cycle
-export PDYHH_cycm1=$($NDATE -01  "${PDYHH}")
-export PDYHH_cycp1=$($NDATE +01  "${PDYHH}")
-
-export FGS_OPT=${FGS_OPT:-1}
-
 #################################################
 # Set up the INPUT and OUTPUT directories
 #################################################
 export COMIN=${COMIN:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
 export COMOUT=${COMOUT:-${COMROOT}/${NET}/${envir}/${RUN}.${PDY}}
 
-### Observations Products/Input from RAP
-export COMINrap=${COMINrap:-"${COMIN}/rap.${PDY}"}
-export COMINhrrr=${COMINhrrr:-"${COMIN}/hrrr.${PDY}/conus"}
-export COMINlightning=${COMINlightning:-"${COMIN}/lightning.${PDY}"}
-export COMINmosaic=${COMINmosaic:-"${COMIN}/radar.${PDY}"}
-export COMINradar=${COMINradar:-"${COMINRADAR}/radar.${PDY}${cyc}"}
+# Directory to store the firstguess as input for the RTMA3D (NETCDF?) 
 
-### Observations Products/Input for the RTMA3D (prepbufr files) 
-export COMINobsproc_rtma3d=${COMINobsproc_rtma3d:-"${COMIN}/obsprd.${cycle}"}
-
-### Firstguess Products/Input for the RTMA3D (prepbufr files) 
+export COMINrap=${COMINRAP}/rap.${PDY}
+export COMINhrrr=${COMINHRRR}/hrrr.${PDY}/${domain}
+export GESINhrrr=${GESINHRRR}/hrrr/hrrrges_sfc/${domain}
 export GESINhrrr_rtma3d=${GESINhrrr_rtma3d:-"${COMIN}/fgsprd.${cycle}"}
+export PDYHH_cycm1=$($NDATE -01  "${PDYHH}")
+export PDYHH_cycp1=$($NDATE +01  "${PDYHH}")
 
-if [ ! -d "${COMIN}" ] ; then
-   mkdir -p $COMIN
+PDY_cycp1=`echo ${PDYHH_cycp1} | cut -c 1-8`
+
+export COMINhrrr_cycp1=${COMIN}/hrrr.${PDY_cycp1}/${domain}
+
+export FGS_OPT=${FGS_OPT:-1}
+
+# set the file name of the firstguess for rtma3d
+if [ ! "${PROD_HEAD}" ] ; then
+  export ANLrtma3d_FNAME="${RUN}.t${cyc}z.wrf_inout.nc"
+  export FGSrtma3d_FNAME="${RUN}.t${cyc}z.firstguess.nc"
+else
+  export ANLrtma3d_FNAME="${PROD_HEAD}.wrf_inout.nc"
+  export FGSrtma3d_FNAME="${PROD_HEAD}.firstguess.nc"
 fi
+
 if [ ! -d "${COMOUT}" ] ; then
    mkdir -p $COMOUT
 fi
-if [ ! -d "${COMINobsproc_rtma3d}" ] ; then
-# echo " Directory of obs data does NOT exist. Job abort!"
-# err_exit
-  mkdir -p $COMINobsproc_rtma3d
+
+if [ ! -d "${GESINhrrr_rtma3d}" ] ; then
+   mkdir -p $GESINhrrr_rtma3d
+fi
+
+# fgs data from HPSS
+if [ ! -d "${COMINhrrr}" ] ; then
+  ${ECHO} "ERROR: ${COMINhrrr} does not exist!"
+  exit 1
+fi
+if [ ! -d "${COMINhrrr_cycp1}" ] ; then
+  ${ECHO} "ERROR: ${COMINhrrr_cycp1} does not exist!"
+  exit 1
 fi
 
 ###########################################################
-#
-# The following variables are used in exrtma3d_obsprep_radar.ksh
-#
-###########################################################
-
-#   Set the name to the executable
-    export exefile_name_radar=${exefile_name_radar:-"rtma3d_process_mosaic"}
-
-#   Set the path to the GSI static files
-    export FIXgsi=${FIXgsi:-"${FIXrtma3d}/gsi"}
-    export FIXcrtm=${FIXcrtm:-"${FIXrtma3d}/crtm"}
-    export FIXwps=${FIXwps:-"${FIXrtma3d}/wps"}
-
-    export PARMupp=${PARMupp:-"${PARMrtma3d}/upp"}
-    export PARMwrf=${PARMwrf:-"${PARMrtma3d}/wrf"}
-
-    export OBS_USELIST=${OBS_USELIST:-"${FIXrtma3d}/gsi"}
-    export SFCOBS_USELIST=${SFCOBS_USELIST:-"${FIXrtma3d}/gsi"}
-    export AIRCRAFT_REJECT=${AIRCRAFT_REJECT:-"${FIXrtma3d}/gsi"}
-    export SFCOBS_PROVIDER=${SFCOBS_PROVIDER:-"${FIXrtma3d}/gsi"}
-
-##########################################################
 
 ######################
 # Execute the script.
 ######################
-${exSCR_OBSPREP_RADAR:-$HOMErtma3d/scripts/ex${RUN}_obsprep_radar_sub.ksh}
+${exSCR_PREPFGS:-$HOMErtma3d/scripts/ex${RUN}_prepfgs.ksh}
 export err=$?; err_chk
 
 msg="$0 of $job completed normally"
