Updated unified workflow.

diff --git a/jobs/JRTMA3D_PREPOBS b/jobs/JRTMA3D_PREPOBS
--- a/jobs/JRTMA3D_PREPOBS
+++ b/jobs/JRTMA3D_PREPOBS
@@ -104,10 +104,10 @@ if [ ! -d "${COMINrap}" ] ; then
   ${ECHO} "ERROR: ${COMINrap} does not exist!"
   exit 1
 fi
-if [ ! -d "${COMINhrrr}" ] ; then
-  ${ECHO} "ERROR: ${COMINhrrr} does not exist!"
-  exit 1
-fi
+#if [ ! -d "${COMINhrrr}" ] ; then
+#  ${ECHO} "ERROR: ${COMINhrrr} does not exist!"
+#  exit 1
+#fi
 
 ###########################################################
 
