Unifying rt and retro.

diff --git a/jobs/JRTMA3D_CONVENTIONAL b/jobs/JRTMA3D_CONVENTIONAL
--- a/jobs/JRTMA3D_CONVENTIONAL
+++ b/jobs/JRTMA3D_CONVENTIONAL
@@ -11,6 +11,114 @@ set -x
 # if not, they will take the default values which is set 
 # for the NCO running enviroment
 #######################################################
+np=`cat $PBS_NODEFILE | wc -l`
+
+ulimit -s 512000
+
+# Load modules (moved to jobs/launch.sh)
+
+# Set paths to unix commands (moved to xml file)
+
+# Set the path to the ssrc executable
+export SSRC=${GSI_ROOT}/ssrc.exe
+
+# Set the path to the gsi executable
+export ENCODE_TAMDAR=${GSI_ROOT}/process_tamdar_netcdf.exe
+export APPEND_VSESONDE=${GSI_ROOT}/prepbufr_append_vessonndes.exe
+export APPEND_CLAMPS=${GSI_ROOT}/prepbufr_append_clamps.exe
+export APPEND_STICKNET=${GSI_ROOT}/prepbufr_append_sticknet.exe
+
+# Make sure DATAHOME is defined
+if [ ! "${DATAHOME}" ]; then
+  ${ECHO} "ERROR: \$DATAHOME is not defined!"
+  exit 1
+fi
+
+# Make sure GSI_ROOT is defined and exists
+if [ ! "${GSI_ROOT}" ]; then
+  ${ECHO} "ERROR: \$GSI_ROOT is not defined!"
+  exit 1
+fi
+if [ ! -d "${GSI_ROOT}" ]; then
+  ${ECHO} "ERROR: GSI_ROOT directory '${GSI_ROOT}' does not exist!"
+  exit 1
+fi
+
+if [ ! -d "${TAMDAR_ROOT}" ]; then
+  ${ECHO} "ERROR: TAMDAR_ROOT directory '${TAMDAR_ROOT}' does not exist!"
+  exit 1
+fi
+
+# Make sure START_TIME is defined and in the correct format
+if [ ! "${START_TIME}" ]; then
+  ${ECHO} "ERROR: \$START_TIME is not defined!"
+  exit 1
+else
+  if [ `${ECHO} "${START_TIME}" | ${AWK} '/^[[:digit:]]{10}$/'` ]; then
+    export START_TIME=`${ECHO} "${START_TIME}" | ${SED} 's/\([[:digit:]]\{2\}\)$/ \1/'`
+  else
+    if [ ! "`${ECHO} "${START_TIME}" | ${AWK} '/^[[:digit:]]{8}[[:blank:]]{1}[[:digit:]]{2}$/'`" ]; then
+      ${ECHO} "ERROR: start time, '${START_TIME}', is not in 'yyyymmddhh' or 'yyyymmdd hh' format"
+      exit 1
+    fi
+  fi
+  export START_TIME=`${DATE} -d "${START_TIME}"`
+fi
+
+# Make sure PREPBUFR is defined and that the directory exists
+if [ ! "${PREPBUFR}" ]; then
+  ${ECHO} "ERROR: \$PREPBUFR is not defined"
+  exit 1
+fi
+if [ ! -d "${PREPBUFR}" ]; then
+  ${ECHO} "ERROR: directory '${PREPBUFR}' does not exist!"
+  exit 1
+fi
+if [ ! "${PREPBUFR_SAT}" ]; then
+  ${ECHO} "ERROR: \$PREPBUFR_SAT is not defined"
+  exit 1
+fi
+if [ ! -d "${PREPBUFR_SAT}" ]; then
+  ${ECHO} "ERROR: directory '${PREPBUFR_SAT}' does not exist!"
+  exit 1
+fi
+if [ ! "${EARLY}" ]; then
+  ${ECHO} "ERROR: \$EARLY is not defined"
+  exit 1
+fi
+
+# Make sure the ssrc executable exists
+if [ ! -x "${SSRC}" ]; then
+  ${ECHO} "ERROR: ${SSRC} does not exist!"
+  exit 1
+fi
+
+# Make sure the GSI executable exists
+if [ ! -x "${ENCODE_TAMDAR}" ]; then
+  ${ECHO} "ERROR: ${ENCODE_TAMDAR} does not exist!"
+  exit 1
+fi
+
+# Create the obsprd directory if necessary and cd into it
+if [ ! -d "${DATAHOME}" ]; then
+  ${MKDIR} -p ${DATAHOME}
+fi
+cd ${DATAHOME}
+
+# Compute date & time components for prepbufr filename
+export YYYYMMDD=`${DATE} +"%Y%m%d" -d "${START_TIME}"`
+export YYYYMMDDHH=`${DATE} +"%Y%m%d%H" -d "${START_TIME}"`
+export YYYYJJJHH00=`${DATE} +"%Y%j%H00" -d "${START_TIME}"`
+export YYYYJJJHH=`${DATE} +"%Y%j%H" -d "${START_TIME}"`
+export PREYYJJJHH=`${DATE} +"%y%j%H" -d "${START_TIME} 1 hour ago"`
+export YYJJJHH=`${DATE} +"%y%j%H" -d "${START_TIME}"`
+export YYYY=`${DATE} +"%Y" -d "${START_TIME}"`
+export MM=`${DATE} +"%m" -d "${START_TIME}"`
+export DD=`${DATE} +"%d" -d "${START_TIME}"`
+export HH=`${DATE} +"%H" -d "${START_TIME}"`
+export PREYYYYMMDD=`${DATE} +"%Y%m%d" -d "${START_TIME} 1 hour ago"`
+export PREHH=`${DATE} +"%H" -d "${START_TIME} 1 hour ago"`
+
 
 
 ######################
diff --git a/jobs/JRTMA3D_GSI_DIAG b/jobs/JRTMA3D_GSI_DIAG
--- a/jobs/JRTMA3D_GSI_DIAG
+++ b/jobs/JRTMA3D_GSI_DIAG
@@ -11,6 +11,52 @@ set -x
 # if not, they will take the default values which is set 
 # for the NCO running enviroment
 #######################################################
+# loading modules and set common unix commands from outside
+#   in jobs/launch.sh and/or modulefile
+
+ulimit -s 512000
+
+# Make sure DATAHOME is defined and exists
+if [ ! "${DATAHOME}" ]; then
+  ${ECHO} "ERROR: \$DATAHOME is not defined!"
+  exit 1
+fi
+if [ ! -d "${DATAHOME}" ]; then
+  ${ECHO} "ERROR: DATAHOME directory '${DATAHOME}' does not exist!"
+  exit 1
+fi
+
+# Make sure GSI_ROOT is defined and exists
+if [ ! "${GSI_ROOT}" ]; then
+  ${ECHO} "ERROR: \$GSI_ROOT is not defined!"
+  exit 1
+fi
+if [ ! -d "${GSI_ROOT}" ]; then
+  ${ECHO} "ERROR: GSI_ROOT directory '${GSI_ROOT}' does not exist!"
+  exit 1
+fi
+
+# Make sure START_TIME is defined and in the correct format
+if [ ! "${START_TIME}" ]; then
+  ${ECHO} "ERROR: \$START_TIME is not defined!"
+  exit 1
+else
+  if [ `${ECHO} "${START_TIME}" | ${AWK} '/^[[:digit:]]{10}$/'` ]; then
+    export START_TIME=`${ECHO} "${START_TIME}" | ${SED} 's/\([[:digit:]]\{2\}\)$/ \1/'`
+  elif [ ! "`${ECHO} "${START_TIME}" | ${AWK} '/^[[:digit:]]{8}[[:blank:]]{1}[[:digit:]]{2}$/'`" ]; then
+    ${ECHO} "ERROR: start time, '${START_TIME}', is not in 'yyyymmddhh' or 'yyyymmdd hh' format"
+    exit 1
+  fi
+  export START_TIME=`${DATE} -d "${START_TIME}"`
+fi
+
+# Compute date & time components for the analysis time
+export YYMMDDHH=`${DATE} +"%y%m%d%H" -d "${START_TIME}"`
+
+# Create the ram work directory and cd into it
+export workdir=${DATAHOME}/gsiprd
+cd ${workdir}
+
 
 
 ######################
diff --git a/jobs/JRTMA3D_SATELLITE_BUFR b/jobs/JRTMA3D_SATELLITE_BUFR
--- a/jobs/JRTMA3D_SATELLITE_BUFR
+++ b/jobs/JRTMA3D_SATELLITE_BUFR
@@ -12,6 +12,65 @@ set -x
 # for the NCO running enviroment
 #######################################################
 
+# Make sure DATAHOME is defined and exists
+if [ ! "${DATAHOME}" ]; then
+  ${ECHO} "ERROR: \$DATAHOME is not defined!"
+  exit 1
+fi
+if [ ! -d "${DATAHOME}" ]; then
+  ${ECHO} "NOTE: DATAHOME directory '${DATAHOME}' does not exist! make one!"
+fi
+
+if [ ! "${DATAROOT}" ]; then
+  ${ECHO} "ERROR: \$DATAROOT is not defined!"
+  exit 1
+fi
+if [ ! -d "${DATAROOT}" ]; then
+  ${ECHO} "ERROR: DATAROOT directory '${DATAROOT}' does not exist!"
+  exit 1
+fi
+
+if [ ! "${NASALARC_DATA}" ]; then
+  ${ECHO} "ERROR: \$NASALARC_DATA is not defined!"
+  exit 1
+fi
+if [ ! -d "${NASALARC_DATA}" ]; then
+  ${ECHO} "ERROR: NASALARC_DATA directory '${NASALARC_DATA}' does not exist!"
+  exit 1
+fi
+
+# Make sure GSI_ROOT is defined and exists
+if [ ! "${GSI_ROOT}" ]; then
+  ${ECHO} "ERROR: \$GSI_ROOT is not defined!"
+  exit 1
+fi
+if [ ! -d "${GSI_ROOT}" ]; then
+  ${ECHO} "ERROR: GSI_ROOT directory '${GSI_ROOT}' does not exist!"
+  exit 1
+fi
+
+# Make sure START_TIME is defined and in the correct format
+if [ ! "${START_TIME}" ]; then
+  ${ECHO} "ERROR: \$START_TIME is not defined!"
+  exit 1
+else
+  if [ `${ECHO} "${START_TIME}" | ${AWK} '/^[[:digit:]]{10}$/'` ]; then
+    export START_TIME=`${ECHO} "${START_TIME}" | ${SED} 's/\([[:digit:]]\{2\}\)$/ \1/'`
+  elif [ ! "`${ECHO} "${START_TIME}" | ${AWK} '/^[[:digit:]]{8}[[:blank:]]{1}[[:digit:]]{2}$/'`" ]; then
+    ${ECHO} "ERROR: start time, '${START_TIME}', is not in 'yyyymmddhh' or 'yyyymmdd hh' format"
+    exit 1
+  fi
+  export START_TIME=`${DATE} -d "${START_TIME}"`
+fi
+
+# Compute date & time components for the analysis time
+export YYYYMMDDHH=`${DATE} +"%Y%m%d%H" -d "${START_TIME}"`
+export YYYYJJJ=`${DATE} +"%Y%j" -d "${START_TIME}"`
+export YYYYJJJHH=`${DATE} +"%Y%j%H" -d "${START_TIME}"`
+export YYYYJJJ12=`${DATE} +"%Y%j" -d "${START_TIME} 1 hours ago "`
+export HH=`${DATE} +"%H" -d "${START_TIME}"`
+export HH12=`${DATE} +"%H" -d "${START_TIME} 1 hours ago "`
+
 
 ######################
 # Execute the script.
diff --git a/jobs/JRTMA3D_SMARTINIT_BL b/jobs/JRTMA3D_SMARTINIT_BL
--- a/jobs/JRTMA3D_SMARTINIT_BL
+++ b/jobs/JRTMA3D_SMARTINIT_BL
@@ -11,9 +11,64 @@ set -x
 # if not, they will take the default values which is set 
 # for the NCO running enviroment
 #######################################################
+# Print run parameters
+${ECHO}
+${ECHO} "smartinit.sh started at `${DATE}`"
+${ECHO}
+${ECHO} "DATAHOME = ${DATAHOME}"
+${ECHO} "     EXE_ROOT = ${EXE_ROOT}"
+
+# Set up some constants
+if [ "${MODEL}" == "HRRR" ]; then
+  export POST=${EXE_ROOT}/hrrr_smartinit_conus
+  export CORE=RAPR
+fi
+
+# Check to make sure the EXE_ROOT var was specified
+if [ ! -d ${EXE_ROOT} ]; then
+   ${ECHO} "ERROR: EXE_ROOT, '${EXE_ROOT}', does not exist"
+   exit 1
+fi
+
+# Check to make sure the post executable exists
+if [ ! -x ${POST} ]; then
+  ${ECHO} "ERROR: ${POST} does not exist, or is not executable"
+  exit 1
+fi
+
+# Check to make sure that the DATAHOME exists
+if [ ! ${DATAROOT} ]; then
+  ${ECHO} "ERROR: DATAROOT, \$DATAROOT , is not defined"
+  exit 1
+fi
+
+# If START_TIME is not defined, use the current time
+if [ ! "${START_TIME}" ]; then
+  export START_TIME=`${DATE} +"%Y%m%d %H"`
+else
+  if [ `${ECHO} "${START_TIME}" | ${AWK} '/^[[:digit:]]{10}$/'` ]; then
+    export START_TIME=`${ECHO} "${START_TIME}" | ${SED} 's/\([[:digit:]]\{2\}\)$/ \1/'`
+  elif [ ! "`${ECHO} "${START_TIME}" | ${AWK} '/^[[:digit:]]{8}[[:blank:]]{1}[[:digit:]]{2}$/'`" ]; then
+    ${ECHO} "ERROR: start time, '${START_TIME}', is not in 'yyyymmddhh' or 'yyyymmdd hh' format"
+    exit 1
+  fi
+  export START_TIME=`${DATE} -d "${START_TIME}"`
+fi
+
+# Print out times
+${ECHO} "   START TIME = "`${DATE} +%Y%m%d%H -d "${START_TIME}"`
+${ECHO} "    FCST_TIME = ${FCST_TIME}"
+
+export STARTTIME_STR=`${DATE} +%Y%m%d%H -d "${START_TIME}"`
 
 
-######################
+ompute date & time components for the analysis time
+export YYYYMMDDHH=`${DATE} +"%Y%m%d%H" -d "${START_TIME}"`
+export HH=`${DATE} +"%H" -d "${START_TIME}"`
+
+export cyc=${HH}
+export fhr=${FCST_TIME}
+`
 # Execute the script.
 ######################
 # ${exSCR_SMARTINIT_BL:-$HOMErtma3d/scripts/${RUN}/ex${RUN}_smartinit_bl.ksh}
diff --git a/jobs/JRTMA3D_UNIPOST b/jobs/JRTMA3D_UNIPOST
--- a/jobs/JRTMA3D_UNIPOST
+++ b/jobs/JRTMA3D_UNIPOST
@@ -11,9 +11,98 @@ set -x
 # if not, they will take the default values which is set 
 # for the NCO running enviroment
 #######################################################
+# Make sure we are using GMT time zone for time computations
+
+export np=`cat $PBS_NODEFILE | wc -l`
+
+export TZ="GMT"
+
+# Set up paths to shell commands (in xml file)
+
+export CRTM="/mnt/lfs1/projects/rtwbl/mhu/code/CRTM_v2.2.6"
+
+# Print run parameters
+${ECHO}
+${ECHO} "unipost.ksh started at `${DATE}`"
+${ECHO}
+${ECHO} "DATAHOME = ${DATAHOME}"
+${ECHO} "     EXE_ROOT = ${EXE_ROOT}"
+
+# Set up some constants
+if [ "${MODEL}" == "RAP" ]; then
+  export POST=${EXE_ROOT}/ncep_post.exe
+  export CORE=RAPR
+elif [ "${MODEL}" == "WRF-RR NMM" ]; then
+  export POST=${EXE_ROOT}/ncep_post.exe
+  export CORE=NMM
+fi
+
+# Check to make sure the EXE_ROOT var was specified
+if [ ! -d ${EXE_ROOT} ]; then
+  ${ECHO} "ERROR: EXE_ROOT, '${EXE_ROOT}', does not exist"
+  exit 1
+fi
+
+# Check to make sure the post executable exists
+if [ ! -x ${POST} ]; then
+  ${ECHO} "ERROR: ${POST} does not exist, or is not executable"
+  exit 1
+fi
+
+# Check to make sure that the DATAHOME exists
+if [ ! ${DATAHOME} ]; then
+  ${ECHO} "ERROR: DATAHOME, \$DATAHOME, is not defined"
+  exit 1
+fi
+
+# Check to make sure that the POST_NAME exists
+if [ ! ${POST_NAME} ]; then
+  ${ECHO} "ERROR: POST_NAME, \$POST_NAME, is not defined"
+  exit 1
+fi
+
+# If START_TIME is not defined, use the current time
+if [ ! "${START_TIME}" ]; then
+  export START_TIME=`${DATE} +"%Y%m%d %H"`
+else
+  if [ `${ECHO} "${START_TIME}" | ${AWK} '/^[[:digit:]]{10}$/'` ]; then
+    export START_TIME=`${ECHO} "${START_TIME}" | ${SED} 's/\([[:digit:]]\{2\}\)$/ \1/'`
+  elif [ ! "`${ECHO} "${START_TIME}" | ${AWK} '/^[[:digit:]]{8}[[:blank:]]{1}[[:digit:]]{2}$/'`" ]; then
 
 
-######################
+#####################HO} "ERROR: start time, '${START_TIME}', is not in 'yyyymmddhh' or 'yyyymmdd hh' format"
+    exit 1
+  fi
+  export START_TIME=`${DATE} -d "${START_TIME}"`
+fi
+
+# Print out times
+${ECHO} "   START TIME = "`${DATE} +%Y%m%d%H -d "${START_TIME}"`
+${ECHO} "    FCST_TIME = ${FCST_TIME}"
+
+export STARTTIME_STR=`${DATE} +%Y%m%d%H -d "${START_TIME}"`
+
+# Set up the work directory and cd into it
+export workdir=${DATAHOME}/${FCST_TIME}
+${RM} -rf ${workdir}
+${MKDIR} -p ${workdir}
+cd ${workdir}
+
+# Set up some constants
+export XLFRTEOPTS="unit_vars=yes"
+export MP_SHARED_MEMORY=yes
+export SPLNUM=47
+export SPL=2.,5.,7.,10.,20.,30.\
+,50.,70.,75.,100.,125.,150.,175.,200.,225.\
+,250.,275.,300.,325.,350.,375.,400.,425.,450.\
+,475.,500.,525.,550.,575.,600.,625.,650.\
+,675.,700.,725.,750.,775.,800.,825.,850.\
+,875.,900.,925.,950.,975.,1000.,1013.2
+
+
+export timestr=`${DATE} +%Y-%m-%d_%H_%M_%S -d "${START_TIME}  ${FCST_TIME} hours"`
+export timestr2=`${DATE} +%Y-%m-%d_%H:%M:%S -d "${START_TIME}  ${FCST_TIME} hours"`
+
 # Execute the script.
 ######################
 # ${exSCR_UNIPOST:-$HOMErtma3d/scripts/${RUN}/ex${RUN}_unipost.ksh}
